version: '3'

services:
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "3000:80"
    volumes:
      - "./frontend:/usr/share/nginx/html"

  backend:
    container_name: backend
    build: ./backend